# Generated by Django 5.1.5 on 2025-05-08 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incoming_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=50)),
                ('order_date', models.DateField(default=datetime.date(2025, 5, 8))),
                ('expected_arrival', models.DateField()),
                ('arrived_check', models.BooleanField(default=False)),
                ('supplier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('stock_quantity', models.PositiveIntegerField()),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('popularity', models.CharField(max_length=100)),
                ('sold', models.PositiveIntegerField()),
                ('incoming_stock', models.PositiveIntegerField()),
                ('delivered_check', models.BooleanField(default=False)),
                ('recommending_stock_number', models.PositiveIntegerField()),
                ('mou', models.PositiveIntegerField()),
            ],
        ),
    ]
