# Generated by Django 5.1.5 on 2025-05-16 13:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('popularity', models.CharField(max_length=100)),
                ('stock_o', models.PositiveIntegerField()),
                ('stock_e', models.PositiveIntegerField()),
                ('sold', models.PositiveIntegerField()),
                ('incoming_stock', models.PositiveIntegerField()),
                ('mou', models.PositiveIntegerField()),
                ('arrived_check', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('popularity', models.CharField(max_length=100)),
                ('stock_o', models.PositiveIntegerField()),
                ('stock_e', models.PositiveIntegerField()),
                ('sold', models.PositiveIntegerField()),
                ('incoming_stock', models.PositiveIntegerField()),
                ('sug_reorder', models.PositiveIntegerField()),
                ('mou', models.PositiveIntegerField()),
                ('arrived_check', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IncomingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('expected_arrival', models.DateField(blank=True, null=True)),
                ('arrived_check', models.BooleanField(default=False)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemist.product')),
            ],
        ),
    ]
