# Generated by Django 5.1.5 on 2025-05-08 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming_order',
            name='expected_arrival',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incoming_order',
            name='order_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
