# Generated by Django 5.1.5 on 2025-05-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysales',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='dailysales',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='dailysales',
            name='retail_price',
        ),
    ]
