# Generated by Django 5.1.5 on 2025-05-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemist', '0002_alter_incoming_order_expected_arrival_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('stock_quantity', models.PositiveIntegerField()),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('popularity', models.CharField(max_length=100)),
                ('sold', models.PositiveIntegerField()),
                ('incoming_stock', models.PositiveIntegerField()),
                ('delivered_check', models.BooleanField(default=False)),
                ('recommending_stock_number', models.PositiveIntegerField()),
                ('mou', models.PositiveIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
