# Generated by Django 5.1.5 on 2025-05-15 01:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemist', '0003_dailysales'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('expected_arrival', models.DateField(blank=True, null=True)),
                ('arrived_check', models.BooleanField(default=False)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemist.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Incoming_Order',
        ),
    ]
